const LAPTOP_DATA = [
    {
        "name": "HP 15-FD1471TU",
        "brand": "HP",
        "price_thb": 24490,
        "cpu_model": "Intel Core Ultra 7 155H",
        "cpu_cores": 16,
        "cpu_ghz": 1.4,
        "ram_gb": 24,
        "ram_type": "DDR5",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel Arc Graphics",
        "gpu_vram_gb": 0,
        "llm_performance_score": 95,
        "shop_url": "https://www.jib.co.th/web/product/readProduct/82278/25/NOTEBOOK--โน้ตบุ๊ค--HP-15-FD1471TU---SILVER",
        "image_url": "images/HP_15-FD1471TU.png",
        "last_updated": "2024-05-02"
    },
    {
        "name": "Lenovo IdeaPad Slim 3 16IRH10",
        "brand": "Lenovo",
        "price_thb": 22990,
        "cpu_model": "Intel Core i7-13620H",
        "cpu_cores": 10,
        "cpu_ghz": 2.4,
        "ram_gb": 16,
        "ram_type": "DDR5",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel UHD Graphics",
        "gpu_vram_gb": 0,
        "llm_performance_score": 88,
        "shop_url": "https://www.advice.co.th/product/notebook/notebook-lenovo/notebook-lenovo-ideapad-slim-3-16irh10-83k2007sta-cosmic-blue-",
        "image_url": "images/Lenovo_IdeaPad_Slim_3_16IRH10.jpg",
        "last_updated": "2024-05-02"
    },
    {
        "name": "Lenovo IdeaPad Slim 3 16AHP10",
        "brand": "Lenovo",
        "price_thb": 24490,
        "cpu_model": "AMD Ryzen 7 8840HS",
        "cpu_cores": 8,
        "cpu_ghz": 3.3,
        "ram_gb": 16,
        "ram_type": "DDR5",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "AMD Radeon Graphics",
        "gpu_vram_gb": 0,
        "llm_performance_score": 87,
        "shop_url": "https://www.advice.co.th/product/notebook/notebook-lenovo/notebook-lenovo-ideapad-slim-3-16ahp10-83kb0030ta-luna-grey-",
        "image_url": "images/Lenovo_IdeaPad_Slim_3_16AHP10.jpg",
        "last_updated": "2024-05-02"
    },
    {
        "name": "Lenovo IdeaPad Slim 5 16IMH9",
        "brand": "Lenovo",
        "price_thb": 27990,
        "cpu_model": "Intel Core Ultra 5 125H",
        "cpu_cores": 14,
        "cpu_ghz": 1.2,
        "ram_gb": 16,
        "ram_type": "LPDDR5X",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel Arc Graphics",
        "gpu_vram_gb": 0,
        "llm_performance_score": 82,
        "shop_url": "https://www.advice.co.th/product/notebook/notebook-lenovo/notebook-lenovo-ideapad-slim-5-16imh9-83dc00a3ta-cloud-grey-",
        "image_url": "images/Lenovo_IdeaPad_Slim_5_16IMH9.jpg",
        "last_updated": "2024-05-02"
    },
    {
        "name": "ASUS Vivobook 15 X1502VA",
        "brand": "ASUS",
        "price_thb": 20490,
        "cpu_model": "Intel Core i5-13420H",
        "cpu_cores": 8,
        "cpu_ghz": 2.1,
        "ram_gb": 16,
        "ram_type": "DDR4",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel UHD Graphics",
        "gpu_vram_gb": 0,
        "llm_performance_score": 78,
        "shop_url": "https://www.jib.co.th/web/product/readProduct/81412/25/NOTEBOOK--โน้ตบุ๊ค--ASUS-VIVOBOOK-15-X1502VA-BQ590WA---QUIET-BLUE",
        "image_url": "images/ASUS_Vivobook_15_X1502VA.png",
        "last_updated": "2024-05-02"
    },
    {
        "name": "ASUS Vivobook 17 X1704VA",
        "brand": "ASUS",
        "price_thb": 25990,
        "cpu_model": "Intel Core i5-1335U",
        "cpu_cores": 10,
        "cpu_ghz": 1.3,
        "ram_gb": 16,
        "ram_type": "DDR4",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel Iris Xe",
        "gpu_vram_gb": 0,
        "llm_performance_score": 75,
        "shop_url": "https://www.advice.co.th/product/notebook/notebook-asus/notebook-asus-vivobook-17-x1704va-au523wa-quiet-blue-",
        "image_url": "images/ASUS_Vivobook_17_X1704VA.jpg",
        "last_updated": "2024-05-02"
    },
    {
        "name": "Dell Inspiron 15 3530",
        "brand": "Dell",
        "price_thb": 17990,
        "cpu_model": "Intel Core i5-1334U",
        "cpu_cores": 10,
        "cpu_ghz": 1.3,
        "ram_gb": 16,
        "ram_type": "DDR4",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel UHD Graphics",
        "gpu_vram_gb": 0,
        "llm_performance_score": 72,
        "shop_url": "https://www.jib.co.th/web/product/readProduct/79535/25/NOTEBOOK--โน้ตบุ๊ค--DELL-15-DC15250I5161---PLATINUM-SILVER",
        "image_url": "images/Dell_Inspiron_15_3530.jpg",
        "last_updated": "2024-05-02"
    },
    {
        "name": "ASUS Vivobook 16 X1607CA",
        "brand": "ASUS",
        "price_thb": 23990,
        "cpu_model": "Intel Core i5-120U",
        "cpu_cores": 10,
        "cpu_ghz": 1.4,
        "ram_gb": 16,
        "ram_type": "DDR4",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel Graphics",
        "gpu_vram_gb": 0,
        "llm_performance_score": 70,
        "shop_url": "https://www.advice.co.th/product/notebook/notebook-asus/notebook-asus-vivobook-16-x1607ca-mb535wa-indie-black-",
        "image_url": "images/ASUS_Vivobook_16_X1607CA.jpg",
        "last_updated": "2024-05-02"
    },
    {
        "name": "Acer Aspire 5 A515-58M",
        "brand": "Acer",
        "price_thb": 18900,
        "cpu_model": "Intel Core i5-1335U",
        "cpu_cores": 10,
        "cpu_ghz": 1.3,
        "ram_gb": 16,
        "ram_type": "LPDDR5",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel Iris Xe",
        "gpu_vram_gb": 0,
        "llm_performance_score": 74,
        "shop_url": "https://www.advice.co.th/product/notebook/notebook-acer/notebook-acer-aspire-5-a515-58m-56u6-steel-gray-",
        "image_url": "images/Acer_Aspire_5_A515-58M.jpg",
        "last_updated": "2024-05-02"
    },
    {
        "name": "MSI Modern 15 B13M",
        "brand": "MSI",
        "price_thb": 19990,
        "cpu_model": "Intel Core i5-1335U",
        "cpu_cores": 10,
        "cpu_ghz": 1.3,
        "ram_gb": 16,
        "ram_type": "DDR4",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel Iris Xe",
        "gpu_vram_gb": 0,
        "llm_performance_score": 73,
        "shop_url": "https://www.jib.co.th/web/product/readProduct/58421/25/NOTEBOOK--โน้ตบุ๊ค--MSI-MODERN-15-B13M-442TH---CLASSIC-BLACK",
        "image_url": "images/MSI_Modern_15_B13M.jpg",
        "last_updated": "2024-05-02"
    },
    {
        "name": "Lenovo LOQ 15IAX9",
        "brand": "Lenovo",
        "price_thb": 26990,
        "cpu_model": "Intel Core i5-12450HX",
        "cpu_cores": 8,
        "cpu_ghz": 2.4,
        "ram_gb": 16,
        "ram_type": "DDR5",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "NVIDIA GeForce RTX 2050",
        "gpu_vram_gb": 4,
        "llm_performance_score": 86,
        "shop_url": "https://www.jib.co.th/web/product/readProduct/66205/25/NOTEBOOK--โน้ตบุ๊ค--LENOVO-LOQ-15IAX9-83GS003XTA---LUNA-GREY",
        "image_url": "images/Lenovo_LOQ_15IAX9.jpg",
        "last_updated": "2024-05-03"
    },
    {
        "name": "Acer Nitro V 15 ANV15-51",
        "brand": "Acer",
        "price_thb": 25990,
        "cpu_model": "Intel Core i5-13420H",
        "cpu_cores": 8,
        "cpu_ghz": 2.1,
        "ram_gb": 16,
        "ram_type": "DDR5",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "NVIDIA GeForce RTX 2050",
        "gpu_vram_gb": 4,
        "llm_performance_score": 85,
        "shop_url": "https://www.advice.co.th/product/notebook/notebook-acer/notebook-acer-nitro-v-15-anv15-51-54p3-obsidian-black-",
        "image_url": "images/Acer_Nitro_V_15_ANV15-51.jpg",
        "last_updated": "2024-05-03"
    },
    {
        "name": "HP Victus 15-fb2028AX",
        "brand": "HP",
        "price_thb": 24990,
        "cpu_model": "AMD Ryzen 5 7535HS",
        "cpu_cores": 6,
        "cpu_ghz": 3.3,
        "ram_gb": 16,
        "ram_type": "DDR5",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "NVIDIA GeForce RTX 2050",
        "gpu_vram_gb": 4,
        "llm_performance_score": 84,
        "shop_url": "https://www.jib.co.th/web/product/readProduct/75082/25/NOTEBOOK--โน้ตบุ๊ค--HP-VICTUS-15-FB2028AX---MICA-SILVER",
        "image_url": "images/HP_Victus_15-fb2028AX.jpg",
        "last_updated": "2024-05-03"
    },
    {
        "name": "MSI Thin 15 B12UC-1418TH",
        "brand": "MSI",
        "price_thb": 23990,
        "cpu_model": "Intel Core i5-12450H",
        "cpu_cores": 8,
        "cpu_ghz": 2.0,
        "ram_gb": 16,
        "ram_type": "DDR4",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "NVIDIA GeForce RTX 3050",
        "gpu_vram_gb": 4,
        "llm_performance_score": 87,
        "shop_url": "https://www.jib.co.th/web/product/readProduct/66304/25/NOTEBOOK--โน้ตบุ๊ค--MSI-THIN-15-B12UC-1418TH---COSMOS-GRAY",
        "image_url": "images/MSI_Thin_15_B12UC-1418TH.jpg",
        "last_updated": "2024-05-03"
    },
    {
        "name": "Huawei MateBook D 14 2024",
        "brand": "Huawei",
        "price_thb": 21990,
        "cpu_model": "Intel Core i5-13420H",
        "cpu_cores": 8,
        "cpu_ghz": 2.1,
        "ram_gb": 16,
        "ram_type": "LPDDR5",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel UHD Graphics",
        "gpu_vram_gb": 0,
        "llm_performance_score": 77,
        "shop_url": "https://consumer.huawei.com/th/laptops/matebook-d-14-2024/",
        "image_url": "images/Huawei_MateBook_D_14_2024.jpg",
        "last_updated": "2024-05-03"
    },
    {
        "name": "Acer Swift Go 14 SFG14-73-50XV",
        "brand": "Acer",
        "price_thb": 29990,
        "cpu_model": "Intel Core Ultra 5 125H",
        "cpu_cores": 14,
        "cpu_ghz": 1.2,
        "ram_gb": 16,
        "ram_type": "LPDDR5X",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel Arc Graphics",
        "gpu_vram_gb": 0,
        "llm_performance_score": 82,
        "shop_url": "https://www.advice.co.th/product/notebook/notebook-acer/notebook-acer-swift-go-14-sfg14-73-50xv-silver-",
        "image_url": "images/Acer_Swift_Go_14_SFG14-73-50XV.jpg",
        "last_updated": "2024-05-03"
    },
    {
        "name": "Honor MagicBook X 16 2024",
        "brand": "Honor",
        "price_thb": 19990,
        "cpu_model": "Intel Core i5-12450H",
        "cpu_cores": 8,
        "cpu_ghz": 2.0,
        "ram_gb": 16,
        "ram_type": "LPDDR4X",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel UHD Graphics",
        "gpu_vram_gb": 0,
        "llm_performance_score": 76,
        "shop_url": "https://www.honor.com/th/laptops/honor-magicbook-x-16-2024/",
        "image_url": "images/Honor_MagicBook_X_16_2024.jpg",
        "last_updated": "2024-05-03"
    },
    {
        "name": "Acer Aspire 3 A315-510P-389D",
        "brand": "Acer",
        "price_thb": 15900,
        "cpu_model": "Intel Core i3-N305",
        "cpu_cores": 8,
        "cpu_ghz": 1.8,
        "ram_gb": 16,
        "ram_type": "LPDDR5",
        "storage_gb": 512,
        "storage_type": "SSD",
        "gpu_model": "Intel UHD Graphics",
        "gpu_vram_gb": 0,
        "llm_performance_score": 55,
        "shop_url": "https://www.advice.co.th/product/notebook/notebook-acer/notebook-acer-aspire-3-a315-510p-389d-pure-silver-",
        "image_url": "images/Acer_Aspire_3_A315-510P-389D.jpg",
        "last_updated": "2024-05-03"
    }
];
